theme: jekyll-theme-minimal

title: UK Systems Research
description: Collating news and events for the UK Systems Research Community

## jekyll configuration for GitHub Pages
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  hard_wrap: false
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    bold_every: 5

## my configuration
exclude: [Makefile, README.md]
include: [.well-known]
permalink: pretty

navigation:
- text: home
  url: /
- text: workshop
  url: /workshop/
